# Generated by Django 5.1.2 on 2024-10-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base_app', '0002_book_cover_image_book_description_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
